source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CCDJoystick_Example', :exclusive => true do
  pod "CCDJoystick", :path => "../"
end

target 'CCDJoystick_Tests', :exclusive => true do
  pod "CCDJoystick", :path => "../"

  
end
